version: '3.9'

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: go3pos_site
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - VIRTUAL_HOST=www.go3pos.com,go3pos.com
    depends_on:
      - php
    networks:
      - services_multiple_site

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: go3pos_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:9000"
    networks:
      - services_multiple_site
    external_links:
      - mysql:mysql
      - redis:redis

networks:
  services_multiple_site:
    external: true